version: "3.7"

services:

    traefik:
        image: traefik:${TRAEFIK_TAG}
        container_name: "${PROXY_NETWORK}-traefik"
        volumes:
        - ./traefik.toml:/etc/traefik/traefik.toml
        - /var/run/docker.sock:/var/run/docker.sock
        # see https://github.com/containous/traefik/issues/7
        command:
            # - "--idletimeout=60s"
            # - "--retry.attempts=100"
            # - "--forwardingtimeouts.responseheadertimeout=60s"
            - "--debug=${TRAEFIK_DEBUG}"
            - "--logLevel=${TRAEFIK_LOG_LEVEL}"
            - "--api"
            - "--docker"
            - "--web"
            - "--docker.watch=true"
            - "--docker.domain=${TRAEFIK_DOCKER_DOMAIN}"
        labels:
            - "traefik.docker.network=${PROXY_NETWORK}}"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:traefik.${TRAEFIK_DOCKER_DOMAIN}"
        networks:
            0_proxy:
                aliases:
                - traefik.${TRAEFIK_DOCKER_DOMAIN}
        ports:
        - '80:80'
        - '8080:8080'
        - '443:443'

networks:
    0_proxy:
        driver: bridge
        name: "${PROXY_NETWORK}"
